name: ubuntu

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Prepare for Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
            mkdir -p test
            cd test
            toolzip=nuclei_riscv_newlibc_prebuilt_linux64_2020.08.tar.bz2
            if [ ! -e $toolzip ] ; then
              wget https://nucleisys.com/upload/files/toochain/gcc/$toolzip
            fi
            tar -xjf $toolzip
            cd ..
            echo "NUCLEI_TOOL_ROOT=$(pwd)/test" > setup_config.sh

      - name: Build
        run: |
          echo "Setup build environment"
          touch build.log
          export CORE=n205
          echo "build test"  >> build.log
          cd board-manager & make
          mv build.log build_eval.log

      - name: Upload Log
        uses: actions/upload-artifact@v2.2.0
        with:
          name: upload_log
          path: |
            build*.log
